### ISSUE TITLE
Adopt the library to HTML changes of GitHub

### ISSUE THREAD

**Issue by Sharaal** [ecrmnn/trending-github#4]
Hey, it seems there are changes in the HTML of GitHub and the library doesn't return any trending now. It would be nice to get an updated version aligned to the changes.

What I changed to fix it on my side:
* Repository containers: `$('li', 'ol.repo-list')` => `$('article')`
* Title: `$(repo).find('h3')` => `$(repo).find('h1.h3 a')`
* Description: `$(repo).find('.py-1 > p')` => `$(repo).find('p')`

With these changes all data are filled except the amount of forks which is not anymore available.

Care about maybe there are different layouts, so it's maybe needed to support multiple ones and the selectors are relative general and it's maybe worth to exchange them with more precise ones.

**Comment by ecrmnn** [comment]
Thanks for letting me know 👏
