### ISSUE TITLE
Title format changed, author wrong, title not extracted anymore

### ISSUE THREAD

**Issue by Sharaal** [ecrmnn/trending-github#6]
Hi,

I currently have the problem that the `name` is always `undefined`. After a bit research of the rootcause it seems GitHub changed the format of the title and added `\n` after the `/`, so the split doesn't work anymore.

It seems it can be easily fixed by changing line 23 to:
```typescript
const var title = $(repo).find('h1.h3 a').text().replace(/\s/g, '');
```

and line 29/30 to:
```typescript
   author: title.split('/')[0],
   name: title.split('/')[1],
```

After that change it works for me locally and in my little project, see https://github-rssfeeds.herokuapp.com/trending.

**Comment by ecrmnn** [comment]
Thanks for reporting this! I had overlooked an email from Travis regarding this issue. Fixed in `2.0.1`

**Comment by Sharaal** [comment]
Thx, if the fixed version will be published, I can check it. :)

**Comment by Sharaal** [comment]
Version is published, fix works. So, thx. :)
